"""Premium theme: a small design system -> one scoped CSS file (assets/kunergy-premium.css).

Everything is scoped under `body.kg-premium`, so it can be switched off by removing one class/link.
No external fonts or scripts (fast, private, nothing to break).
"""
from __future__ import annotations

import hashlib
import re
from collections import Counter

import yaml

from .config import DATA_DIR
from .tools.text import soup_of

THEME_PATH = DATA_DIR / "theme.yaml"
CSS_PATH = "assets/kunergy-premium.css"

PALETTES = {
    "solar_green": {"label": "Solar Green & Gold", "primary": "#0B6B3A", "dark": "#083D26", "accent": "#F5A623", "bg": "#FFFFFF", "bg_alt": "#F4F8F5", "text": "#16231C", "muted": "#5B6B63", "line": "#DDE8E0"},
    "midnight_amber": {"label": "Midnight Blue & Amber", "primary": "#12395F", "dark": "#0A1F36", "accent": "#FFB400", "bg": "#FFFFFF", "bg_alt": "#F2F6FA", "text": "#14202E", "muted": "#586677", "line": "#DCE4EC"},
    "clean_teal": {"label": "Clean Teal & Sun", "primary": "#0E7C86", "dark": "#094F56", "accent": "#FF8A3D", "bg": "#FFFFFF", "bg_alt": "#F1F8F8", "text": "#13262A", "muted": "#58707A", "line": "#D9E8EA"},
}
FONTS = {
    "system": ("system-ui,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif", "system-ui,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"),
    "elegant": ("system-ui,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif", "Georgia,'Times New Roman',serif"),
}
DEFAULT_THEME = {"enabled": True, "palette": "solar_green", "font": "system", "extra_css": ""}


def load_theme() -> dict:
    try:
        d = yaml.safe_load(THEME_PATH.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        d = {}
    return {**DEFAULT_THEME, **d}


def save_theme(theme: dict) -> None:
    THEME_PATH.write_text(yaml.safe_dump({**DEFAULT_THEME, **theme}, sort_keys=False, allow_unicode=True), encoding="utf-8")


def build_css(theme: dict | None = None) -> str:
    t = {**DEFAULT_THEME, **(theme or {})}
    p = PALETTES.get(t["palette"], PALETTES["solar_green"])
    body_font, head_font = FONTS.get(t["font"], FONTS["system"])
    css = f"""/* Kunergy premium theme - generated by SEO Autopilot ({p['label']}). Remove the kg-premium class to disable. */
:root{{--kg-primary:{p['primary']};--kg-dark:{p['dark']};--kg-accent:{p['accent']};--kg-bg:{p['bg']};--kg-alt:{p['bg_alt']};--kg-text:{p['text']};--kg-muted:{p['muted']};--kg-line:{p['line']};--kg-radius:14px;--kg-shadow:0 10px 30px rgba(8,30,20,.10)}}
html{{scroll-behavior:smooth}}
body.kg-premium{{font-family:{body_font};color:var(--kg-text);background:var(--kg-bg);line-height:1.65;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}}
body.kg-premium h1,body.kg-premium h2,body.kg-premium h3,body.kg-premium h4{{font-family:{head_font};color:var(--kg-dark);letter-spacing:-.01em;line-height:1.2}}
body.kg-premium h1{{font-size:clamp(2rem,4.5vw,3.4rem)}}
body.kg-premium h2{{font-size:clamp(1.5rem,3vw,2.2rem);position:relative;padding-bottom:.45em}}
body.kg-premium h2::after{{content:"";position:absolute;left:0;bottom:0;width:56px;height:4px;border-radius:4px;background:var(--kg-accent)}}
body.kg-premium a{{color:var(--kg-primary);transition:color .2s ease}}
body.kg-premium a:hover{{color:var(--kg-accent)}}
body.kg-premium nav a{{font-weight:600}}
body.kg-premium section{{scroll-margin-top:84px}}
body.kg-premium li::marker{{color:var(--kg-accent)}}
body.kg-premium img{{max-width:100%}}
body.kg-premium button,body.kg-premium input[type=submit],body.kg-premium .btn{{background:var(--kg-primary);color:#fff;border:0;border-radius:12px;padding:13px 26px;font-weight:700;font-size:1rem;cursor:pointer;box-shadow:var(--kg-shadow);transition:transform .15s ease,background .2s ease}}
body.kg-premium button:hover,body.kg-premium input[type=submit]:hover,body.kg-premium .btn:hover{{background:var(--kg-dark);color:#fff;transform:translateY(-2px)}}
body.kg-premium input:not([type=submit]):not([type=checkbox]):not([type=radio]),body.kg-premium select,body.kg-premium textarea{{width:100%;max-width:100%;border:1px solid var(--kg-line);border-radius:12px;padding:12px 14px;font:inherit;background:#fff;color:var(--kg-text);box-sizing:border-box}}
body.kg-premium input:focus,body.kg-premium select:focus,body.kg-premium textarea:focus{{outline:3px solid color-mix(in srgb,var(--kg-accent) 45%,transparent);border-color:var(--kg-accent)}}
body.kg-premium footer{{background:var(--kg-dark);color:#E8F0EB}}
body.kg-premium footer a{{color:var(--kg-accent)}}
#kg-service-links{{background:var(--kg-alt);padding:56px 20px}}
#kg-service-links ul{{max-width:1100px;margin:24px auto 0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:16px}}
#kg-service-links h2{{max-width:1100px;margin:0 auto}}
#kg-service-links a{{display:block;padding:18px 20px;background:#fff;border:1px solid var(--kg-line);border-radius:var(--kg-radius);box-shadow:var(--kg-shadow);text-decoration:none;font-weight:600;transition:transform .15s ease,border-color .2s ease}}
#kg-service-links a:hover{{transform:translateY(-3px);border-color:var(--kg-accent)}}
#kg-contact-bar{{background:var(--kg-dark)}}
#kg-contact-bar a{{background:var(--kg-primary);color:#fff}}
#kg-contact-bar a:last-child{{background:var(--kg-accent);color:#1b1b1b}}
@media (min-width:900px){{#kg-contact-bar{{left:auto;right:24px;bottom:24px;width:auto;border-radius:14px;overflow:hidden;box-shadow:var(--kg-shadow)}}#kg-contact-bar a{{padding:12px 20px}}body{{padding-bottom:0!important}}}}
@media (prefers-reduced-motion:reduce){{*{{transition:none!important;scroll-behavior:auto!important}}}}
"""
    extra = (t.get("extra_css") or "").strip()
    if extra:
        css += "\n/* extra */\n" + extra + "\n"
    return css


def css_version(css: str) -> str:
    return hashlib.sha1(css.encode("utf-8")).hexdigest()[:8]


def theme_href(css: str) -> str:
    return f"/{CSS_PATH}?v={css_version(css)}"


def sanitize_css(css: str, max_len: int = 40_000, require_scope: bool = True) -> list[str]:
    """Return a list of problems (empty = safe). Extra (AI/manual) CSS must be scoped under .kg-premium."""
    problems = []
    low = css.lower()
    if len(css) > max_len:
        problems.append("CSS is too large")
    for bad in ("@import", "expression(", "javascript:", "</style", "<script", "-moz-binding"):
        if bad in low:
            problems.append(f"forbidden token: {bad}")
    if re.search(r"(?<![\w-])behavior\s*:", low):
        problems.append("forbidden property: behavior")
    if re.search(r"url\(\s*['\"]?\s*(https?:)?//", low):
        problems.append("external url() is not allowed")
    for m in re.finditer(r"([^{}]+)\{", css if require_scope else ""):
        sel = m.group(1).strip()
        if sel and not sel.startswith("@") and "kg-premium" not in sel and not sel.startswith(("from", "to", ":root", "html")) and not re.fullmatch(r"\d+%", sel):
            problems.append(f'selector not scoped under .kg-premium: "{sel[:60]}"')
    if css.count("{") != css.count("}"):
        problems.append("unbalanced braces")
    return problems


def inventory(html: str) -> dict:
    """What the Designer agent needs to target real selectors on the existing site."""
    soup = soup_of(html)
    classes = Counter(c for t in soup.find_all(True) for c in (t.get("class") or []))
    return {
        "stylesheets": [l.get("href") for l in soup.find_all("link", rel=lambda v: v and "stylesheet" in v) if l.get("href")],
        "top_classes": [c for c, _ in classes.most_common(40)],
        "ids": [t["id"] for t in soup.find_all(id=True)][:40],
        "tags": sorted({t.name for t in soup.find_all(True)} & {"header", "nav", "main", "section", "footer", "form", "button", "table", "ul"}),
        "has_inline_style_attrs": len(soup.find_all(style=True)),
    }


def preview_html(html: str, css: str, base_url: str) -> str:
    """Live-site HTML with the premium CSS applied inline, for a safe preview (nothing is saved)."""
    soup = soup_of(html)
    if soup.head is None or soup.body is None:
        return html
    base = soup.new_tag("base", href=base_url.rstrip("/") + "/")
    soup.head.insert(0, base)
    st = soup.new_tag("style")
    st.string = css
    soup.head.append(st)
    soup.body["class"] = list(soup.body.get("class", [])) + ["kg-premium"]
    return str(soup)


def designer_prompt(inv: dict, theme: dict) -> str:
    p = PALETTES.get(theme.get("palette"), PALETTES["solar_green"])
    return f"""You are refining a premium look for a solar/energy company's existing website.
Existing site inventory: {inv}
Design tokens already defined as CSS variables: --kg-primary {p['primary']}, --kg-dark {p['dark']}, --kg-accent {p['accent']}, --kg-alt {p['bg_alt']}.
A base stylesheet already styles body, headings, links, buttons, forms, footer. Write ONLY extra CSS for the site's real classes/ids above
(hero overlay, card grids, spacing, mobile nav) that improves a premium feel and readability.
Rules: every selector MUST start with `body.kg-premium`; no @import, no external url(), no scripts, under 3000 characters, mobile-first.
Return ONLY JSON: {{"extra_css": "..."}}"""
